name: pictools
description: "跨平台图片处理工具"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0+1
  desktop_drop: ^0.5.0
  provider: ^6.1.2
  image: ^4.7.2
  rust_lib_pictools:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  desktop_multi_window: ^0.3.0
  window_manager: ^0.5.1
  dio: ^5.4.0
  path_provider: ^2.1.0
  path: ^1.9.0
  package_info_plus: ^8.0.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
