// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/background_removal.dart';
import 'api/image_codec.dart';
import 'api/image_enhance.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1063922042;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_pictools',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiBackgroundRemovalAddSolidBackground({
    required List<int> rgbaData,
    required int bgRed,
    required int bgGreen,
    required int bgBlue,
  });

  Future<Uint8List> crateApiImageCodecCropImage({
    required List<int> imageData,
    required int x,
    required int y,
    required int width,
    required int height,
  });

  Future<Uint8List> crateApiImageCodecEncodeImage({
    required List<int> imageData,
    required ImageFormat format,
  });

  Future<Uint8List> crateApiImageEnhanceEnhanceImage({
    required List<int> imageData,
  });

  Future<Uint8List> crateApiBackgroundRemovalRemoveBackground({
    required List<int> imageData,
    required String modelPath,
  });

  Future<Uint8List> crateApiImageCodecResizeImage({
    required List<int> imageData,
    required int width,
    required int height,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiBackgroundRemovalAddSolidBackground({
    required List<int> rgbaData,
    required int bgRed,
    required int bgGreen,
    required int bgBlue,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(rgbaData, serializer);
          sse_encode_u_8(bgRed, serializer);
          sse_encode_u_8(bgGreen, serializer);
          sse_encode_u_8(bgBlue, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBackgroundRemovalAddSolidBackgroundConstMeta,
        argValues: [rgbaData, bgRed, bgGreen, bgBlue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBackgroundRemovalAddSolidBackgroundConstMeta =>
      const TaskConstMeta(
        debugName: "add_solid_background",
        argNames: ["rgbaData", "bgRed", "bgGreen", "bgBlue"],
      );

  @override
  Future<Uint8List> crateApiImageCodecCropImage({
    required List<int> imageData,
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageData, serializer);
          sse_encode_u_32(x, serializer);
          sse_encode_u_32(y, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCodecCropImageConstMeta,
        argValues: [imageData, x, y, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCodecCropImageConstMeta =>
      const TaskConstMeta(
        debugName: "crop_image",
        argNames: ["imageData", "x", "y", "width", "height"],
      );

  @override
  Future<Uint8List> crateApiImageCodecEncodeImage({
    required List<int> imageData,
    required ImageFormat format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageData, serializer);
          sse_encode_box_autoadd_image_format(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCodecEncodeImageConstMeta,
        argValues: [imageData, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCodecEncodeImageConstMeta =>
      const TaskConstMeta(
        debugName: "encode_image",
        argNames: ["imageData", "format"],
      );

  @override
  Future<Uint8List> crateApiImageEnhanceEnhanceImage({
    required List<int> imageData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageEnhanceEnhanceImageConstMeta,
        argValues: [imageData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageEnhanceEnhanceImageConstMeta =>
      const TaskConstMeta(debugName: "enhance_image", argNames: ["imageData"]);

  @override
  Future<Uint8List> crateApiBackgroundRemovalRemoveBackground({
    required List<int> imageData,
    required String modelPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageData, serializer);
          sse_encode_String(modelPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBackgroundRemovalRemoveBackgroundConstMeta,
        argValues: [imageData, modelPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBackgroundRemovalRemoveBackgroundConstMeta =>
      const TaskConstMeta(
        debugName: "remove_background",
        argNames: ["imageData", "modelPath"],
      );

  @override
  Future<Uint8List> crateApiImageCodecResizeImage({
    required List<int> imageData,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageData, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCodecResizeImageConstMeta,
        argValues: [imageData, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCodecResizeImageConstMeta =>
      const TaskConstMeta(
        debugName: "resize_image",
        argNames: ["imageData", "width", "height"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ImageFormat dco_decode_box_autoadd_image_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_format(raw);
  }

  @protected
  ImageFormat dco_decode_image_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ImageFormat_Png();
      case 1:
        return ImageFormat_Jpg(quality: dco_decode_u_8(raw[1]));
      case 2:
        return ImageFormat_WebP(
          quality: dco_decode_u_8(raw[1]),
          lossless: dco_decode_bool(raw[2]),
        );
      case 3:
        return ImageFormat_Bmp();
      case 4:
        return ImageFormat_Ico();
      case 5:
        return ImageFormat_Tiff();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ImageFormat sse_decode_box_autoadd_image_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_format(deserializer));
  }

  @protected
  ImageFormat sse_decode_image_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ImageFormat_Png();
      case 1:
        var var_quality = sse_decode_u_8(deserializer);
        return ImageFormat_Jpg(quality: var_quality);
      case 2:
        var var_quality = sse_decode_u_8(deserializer);
        var var_lossless = sse_decode_bool(deserializer);
        return ImageFormat_WebP(quality: var_quality, lossless: var_lossless);
      case 3:
        return ImageFormat_Bmp();
      case 4:
        return ImageFormat_Ico();
      case 5:
        return ImageFormat_Tiff();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_image_format(
    ImageFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_format(self, serializer);
  }

  @protected
  void sse_encode_image_format(ImageFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ImageFormat_Png():
        sse_encode_i_32(0, serializer);
      case ImageFormat_Jpg(quality: final quality):
        sse_encode_i_32(1, serializer);
        sse_encode_u_8(quality, serializer);
      case ImageFormat_WebP(quality: final quality, lossless: final lossless):
        sse_encode_i_32(2, serializer);
        sse_encode_u_8(quality, serializer);
        sse_encode_bool(lossless, serializer);
      case ImageFormat_Bmp():
        sse_encode_i_32(3, serializer);
      case ImageFormat_Ico():
        sse_encode_i_32(4, serializer);
      case ImageFormat_Tiff():
        sse_encode_i_32(5, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
