// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 使用RMBG-2.0 ONNX模型进行背景移除
///
/// # Arguments
/// * `image_data` - 原始图片数据
/// * `model_path` - ONNX模型文件路径
///
/// # Returns
/// 返回带有透明背景的RGBA图片数据（PNG格式）
Future<Uint8List> removeBackground({
  required List<int> imageData,
  required String modelPath,
}) => RustLib.instance.api.crateApiBackgroundRemovalRemoveBackground(
  imageData: imageData,
  modelPath: modelPath,
);

/// 为透明图片添加纯色背景
///
/// # Arguments
/// * `rgba_data` - RGBA图片数据（PNG格式）
/// * `bg_red` - 背景红色分量 (0-255)
/// * `bg_green` - 背景绿色分量 (0-255)
/// * `bg_blue` - 背景蓝色分量 (0-255)
///
/// # Returns
/// 返回添加了纯色背景的RGB图片数据（PNG格式）
Future<Uint8List> addSolidBackground({
  required List<int> rgbaData,
  required int bgRed,
  required int bgGreen,
  required int bgBlue,
}) => RustLib.instance.api.crateApiBackgroundRemovalAddSolidBackground(
  rgbaData: rgbaData,
  bgRed: bgRed,
  bgGreen: bgGreen,
  bgBlue: bgBlue,
);
