// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'image_codec.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `encode_bmp`, `encode_ico`, `encode_jpg`, `encode_png`, `encode_tiff`, `encode_webp`

Future<Uint8List> encodeImage({
  required List<int> imageData,
  required ImageFormat format,
}) => RustLib.instance.api.crateApiImageCodecEncodeImage(
  imageData: imageData,
  format: format,
);

/// 调整图片尺寸
Future<Uint8List> resizeImage({
  required List<int> imageData,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiImageCodecResizeImage(
  imageData: imageData,
  width: width,
  height: height,
);

/// 裁剪图片
Future<Uint8List> cropImage({
  required List<int> imageData,
  required int x,
  required int y,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiImageCodecCropImage(
  imageData: imageData,
  x: x,
  y: y,
  width: width,
  height: height,
);

@freezed
sealed class ImageFormat with _$ImageFormat {
  const ImageFormat._();

  const factory ImageFormat.png() = ImageFormat_Png;
  const factory ImageFormat.jpg({required int quality}) = ImageFormat_Jpg;
  const factory ImageFormat.webP({
    required int quality,
    required bool lossless,
  }) = ImageFormat_WebP;
  const factory ImageFormat.bmp() = ImageFormat_Bmp;
  const factory ImageFormat.ico() = ImageFormat_Ico;
  const factory ImageFormat.tiff() = ImageFormat_Tiff;
}
