// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dot`, `light_on_kernel`, `pg_exposure_kernel`, `pg_highlights_shadows_kernel`, `pg_highlights_shadows_multiplier`, `pg_linear_to_srgb_alpha`, `pg_linear_to_srgb`, `pg_saturation_kernel`, `pg_srgb_to_linear_alpha`, `pg_srgb_to_linear`

/// 对图片进行亮度增强处理
///
/// # Arguments
/// * `image_data` - 原始图片数据（支持 PNG/JPG/WebP/GIF/BMP 等）
///
/// # Returns
/// 处理后的 PNG 格式图片字节数据
Future<Uint8List> enhanceImage({required List<int> imageData}) =>
    RustLib.instance.api.crateApiImageEnhanceEnhanceImage(imageData: imageData);
